name: Docker Build

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: gdinkar
#  CLUSTER_NAME: my-cluster-name
#  CLUSTER_RESOURCE_GROUP: my-cluster-resource-group
#  NAMESPACE: default
  
jobs:
  build:
    runs-on: ubuntu-latest
    #environment: dev
    steps:
    - uses: actions/checkout@master
    
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/mytestimage:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/mytestimage:${{ github.sha }}