name: Python application Testing

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            python-version: [3.x]

    steps:
    #Code checkout and python setup
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    #Installling all python Dependancies 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install flake8 pytest
        pip install pytest
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    #Python code linting with Flake8   
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    #Python code linting with pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') || true

    #python code test with pytest 
    - name: Test with pytest
      run: |
        export PYTHONPATH=src
        pytest
